development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:644e91413de009813808a44666e801cb@sole.redistogo.com:10669/
  channel_prefix: sidcord_production
